### ISSUE TITLE
Missing timezones

### ISSUE THREAD

**Issue by kyhwana** [avwuff/telegram-plans-bot#1]
Looks like there isn't support for NZT (NZDT OR NZST)
![Screenshot_20230415_205318_Telegram](https://user-images.githubusercontent.com/1559707/232202557-0cc0c5ee-3589-4a2c-81a5-822806bf402b.jpg)

Looking in the locale.go file there's only a few timezones supported?

**Comment by avwuff** [comment]
Yup, just gotta add the rest of them.

If you click the little 4 box icon, a "custom keyboard" comes up that shows you the available time zones.

Now I just need to add all of them.

**Comment by avwuff** [comment]
OK, this is fixed.  The bot now supports ALL time zones, shows you a list of most common ones, and also supports you sending a Location object, and it will automatically figure out the correct time zone for you.
